### ISSUE TITLE
createuser slug not populated

### ISSUE THREAD

**Issue by yalh76** [rhaamo/reel2bits#45]
**Describe the bug**
When using reel2bits fresh install, upload a file give an error:
```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

- [reel2bits-web logs](https://paste.yunohost.org/akogahiben.sql)
- [reel2bits-worker logs](https://paste.yunohost.org/beyayefuya.sql)

**To Reproduce**
1. [Install reel2bits on Yunohost](https://github.com/YunoHost-Apps/reel2bits_ynh/blob/install_remove/scripts/install)
2. Register
3. Click on top left menu `UPLOAD`
3. Click on `Choose a file` and choose an audio file
4. Click on form button `UPLOAD`

**Expected behavior**
Not an error

**Screenshots**
With `DEBUG = True`
![Capture](https://user-images.githubusercontent.com/30271971/56030210-957d6000-5d1c-11e9-80fa-fb3b75eb3e60.PNG)
With `DEBUG = False`
![Capture](https://user-images.githubusercontent.com/30271971/56030397-0886d680-5d1d-11e9-884b-d09013e425dd.PNG)

**Desktop :**
 - OS: windows 10
 - Browser : chrome 73

**Additional context**

1. When manually putting a value to slug field for the user in the postgresql user table, problem is solved
2. slug field is empty when creating user from the website or `flask createuser`

**Comment by rhaamo** [comment]
Thanks for the report !

I thought I had fixed that issue, I will take a look to fix that.

**Comment by rhaamo** [comment]
This should be fixed now, don't hesitate to report back of any issue.

**Comment by yalh76** [comment]
Yep, problem solved
Thanks a lot
